# Get-Pokemon
name: 'Github Action to Get a Pokemon'
description: 'Call an API and get the result'
inputs:
  # access env $INPUT_POKEMON_ID
  pokemon_id:
    description: 'number of the pokemon in the pokedex'
    required: true
    default: 1
outputs:
  pokemon_name:
    description: 'Name of Pokemons'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.pokemon_id}}