on: [push]

jobs:
  custom_test:
    runs-on: ubuntu-latest
    name: We test it locally with act
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
      # Run
      - name: Get Pokemon name
        uses: ./ # Uses an action in the root directory
        id: pokemon
        with:
          pokemon_id: 150
      # Use the pokemon_name output from our action (id:pokemon)
      - name: Get the pokemon
        run: echo "${{ steps.pokemon.outputs.pokemon_name }}"